name: Build and Push to ACR

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      acr_name: rcr777.azurecr.io/twotier

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/action@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
             az acr login --name $acr-name
   
      - name: Build MySQL image
        run: |
             docker build -t $acr-name.azurecr.io/mysql:latest -f mysql/Dockerfile .
   
      - name: Build Flask app image
        run: |
             docker build -t $acr-name.azurecr.io/flask-app:latest .
   
      - name: Push MySQL image to ACR
        run: |
             docker push $acr-name.azurecr.io/mysql:latest
   
      - name: Push Flask app image to ACR
        run: |
             docker push $acr-name.azurecr.io/flask-app:latest